version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todoapp
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
        

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    environment:
      - NODE_ENV=production
      # - NEXT_PUBLIC_API_BASE=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
