services:
  backend:
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/todoapp
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npx nodemon server.js"
    restart: unless-stopped

  frontend:
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      # set your API base for the frontend app if required:
      # - NEXT_PUBLIC_API_BASE=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped